// <auto-generated />
namespace CanView.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Paul_FirstMigrationFixDatatypeError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Paul_FirstMigrationFixDatatypeError));
        
        string IMigrationMetadata.Id
        {
            get { return "201605302235402_Paul_FirstMigrationFixDatatypeError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
