// <auto-generated />
namespace CanView.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Paul_FirstMigrationFixM2MItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Paul_FirstMigrationFixM2MItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201605310118155_Paul_FirstMigrationFixM2MItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
